# Generated by Django 4.0.4 on 2022-06-01 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pelicula', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero_Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lgenero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genero', to='pelicula.genero')),
                ('lpelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pelicula', to='pelicula.pelicula')),
            ],
        ),
    ]
